### ISSUE TITLE
Failure to register a patient to a newly created location as a "Doctor"

### ISSUE THREAD

**Issue by MusinguziMak** [ConnectForLife/cfl-distribution#1]
I believe I have discovered an issue with the patient registration page. 

1. I logged in as default user "admin"
2. Created a new location with all the same tags as the test locations and no child locations
3.  Created a new account. New Person. New User account details had: Privelege level: Doctor, Location: My new location from point 2 above, Capabilities: Administers system, Registers patients
4. Provider Details, Identifier: "Provider1", Provider Role: "Clinical Doctor" 
5. Logged out and logged in again as new user from 3 above. 
6. On trying to create a new patient i get the error "[Failed to resolve location to associate to patient identifiers]". See screenshot
7. I have not added any new Identifiers or changed the original ones in any way as I was just adding a test patient. 
8. I logged in again as Admin and a patient was saved without error.

It seems a Doctor with Registration capability is not able to register a patient. How do I go around this?

![Resolve location to patient identifiers message](https://user-images.githubusercontent.com/43815304/144757374-cc6b3e1f-0985-4164-a41b-b4492c728cb3.png)
.

**Comment by pwargulak** [comment]
Hi @MusinguziMak thank you for the clear description. 
We've been aware of this issue for some time already and the fix is going to be included in the next release - it will happen in the following weeks.

For now, there is a workaround:
1. Create a new Location with name: Unknown Location
2. Change global properties values (Home -> System Administration -> Manage Global Properties)
2.1. locationbasedaccess.access.patient = false
2.2. locationbasedaccess.access.person = false
3. Keep in mind, this will disable filtering of patients on Find Patient page based on their location - any user able to read Patients will see all Patients in the system.

We'll update this thread once the fix is released.

**Comment by pwargulak** [comment]
Hi @MusinguziMak, 
we've released a new version of the Connect for Life Distribution - 2.0.0 - the bug has been fixed.

The demo instance is available here: https://demo.jnj.connect-for-life.org/openmrs

Please feel free to use Github Issues for any other questions, remarks, bugs or features requests.

I'm closing this issue for now.
